params["_key"];_check = player getVariable["ToolsAreOn",false];
if!(_check) then {if(alive player) then {hint format ["Created for the Mantequilla Gang!, have fun %1",name player];diag_log "[ADS] Tools ";player setVariable["ToolsAreOn",true,true];
player addaction ["God Mode ON", {player setVariable ["AdminGod",true,true];player allowDamage false;}, nil, 0, false, true, "", "!(player getVariable['AdminGod',false])"];
player addaction ["God Mode OFF", {player setVariable ["AdminGod",false,true];player allowDamage true;}, nil, 0, false, true, "", "(player getVariable['AdminGod',false])"];player addaction ["Teleport ONCE", {onMapSingleClick "vehicle player setPos _pos; onMapSingleClick '';true;";}, nil, 0, false, true, "", "!(player getVariable['AdminTP',false])"];
player addaction ["Quick Loadout", {removeAllWeapons player;removeAllItems player;removeAllAssignedItems player;removeUniform player;removeVest player;removeBackpack player;removeHeadgear player;removeGoggles player;player forceAddUniform "ALRP_Uniform_Mantequilla1a";player addItemToUniform "FirstAidKit";for "_i" from 1 to 2 do {player addItemToUniform "16Rnd_9x21_Mag";};
player addVest "ALRP_MantequillaVest_vest";for "_i" from 1 to 5 do {player addItemToVest "FirstAidKit";};for "_i" from 1 to 9 do {player addItemToVest "hlc_30rnd_556x45_EPR";};player addBackpack "TRYK_B_Belt_BLK";player addItemToBackpack "ToolKit";player addHeadgear "H_Beret_02";player addGoggles "G_Squares";player addWeapon "alrp_bcmhyperbeast";
player addPrimaryWeaponItem "muzzle_snds_M";player addPrimaryWeaponItem "acc_flashlight";player addPrimaryWeaponItem "optic_DMS";player addPrimaryWeaponItem "bipod_03_F_blk";player addWeapon "hgun_P07_F";player addWeapon "Rangefinder";player linkItem "ItemMap";player linkItem "ItemCompass";player linkItem "Itemwatch";player linkItem "TFAR_anprc152";player linkItem "ItemGPS";
player linkItem "pmc_earpiece";}, nil, 0, false, true, "", "!(player getVariable['QuickLoadout',false])"];systemchat "Created for the Mantequilla Gang by ADS!";player addaction ["Add Map", {player addItem "ItemMap";player assignItem "ItemMap";player setVariable["HaveMap",true];}, nil, 0, false, true, "", "!(player getVariable['HaveMap',false])"];
player addaction ["Add Radio", {player addItem "TFAR_anprc152";player assignItem "TFAR_anprc152";player setVariable["HaveRadio",true];}, nil, 0, false, true, "", "!(player getVariable['HaveRadio',false])"];player addaction ["Debug Console", {createDialog "RscDisplayDebugPublic";}, nil, 0, false, true, "", ""];};};
